---
title: "Contacto efectivo"
author: "Luis Barrios"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE,fig.pos="H"}
knitr::opts_chunk$set(
	echo = FALSE,
	message = FALSE,
	warning = FALSE
)
```

```{r packages}
library(tidyverse)
library(readxl)
library(readr)
library(dplyr)
library(lubridate)
library(tidyr)
library(plotly)


```

```{r reading}
contactoefectivo<-read_xlsx("~/Documentos/GitHub/LabJournalWebsite-master/docs/contactoefectivo.xlsx")
sologestioncomercial<-read_xlsx("~/Documentos/GitHub/LabJournalWebsite-master/docs/sologestioncomercial.xlsx")

```

# Gestión comercial por mes

```{r gestioncomercial}
sologestioncomercial<-sologestioncomercial %>% mutate(year=year(Timestamp))
sologestioncomercial<-sologestioncomercial %>% mutate(mes=month(Timestamp))
sologestioncomercial %>% filter(year==2022) %>% count(mes) %>% ggplot(aes(x=mes,y=n,label=n))+
  geom_bar(stat = "identity",fill="lightblue")+geom_text()
```

# Prestamos con gestión comercial por mes

```{r data_transformation}
prestamosporgestion<-contactoefectivo %>% dplyr::distinct(borrower_id,.keep_all = TRUE)
prestamosporgestion<-prestamosporgestion %>% mutate(year=year(Timestamp))
prestamosporgestion<-prestamosporgestion %>% mutate(mes=month(Timestamp))
ggplotly(prestamosporgestion %>% filter(year==2022) %>% count(mes) %>% ggplot(aes(x=mes,y=n,label=n))+geom_bar(stat = "identity",fill="lightblue")+geom_text())

# nueva transformación
prestamosporgestion$total_months_from_activation[prestamosporgestion$total_months_from_activation>6]<-"Mayor 6 meses"
prestamosporgestion$total_months_from_activation[prestamosporgestion$total_months_from_activation<7]<-"Menor o igual 6 meses"



```

# Cantidad de contactos efectivos por categoría

Dividiendo entre mayor y menor o igual a 6 meses

```{r sadsda}
prestamosporgestion %>% filter(year==2022)  %>% count(mes,total_months_from_activation) %>% 
  ggplot(aes(x=mes,y=n,fill=total_months_from_activation,label=n))+geom_bar(stat = "identity",position = "dodge")+geom_text(position = position_dodge(width = .75))
```

```{r asdasd}
prestamosporgestion %>% count(total_months_from_activation)
```
