---
title: "PQR'S"
output:
  html_document:
    toc: true
    toc_float: false
    collapsed: false
    number_sections: false
    toc_depth: 1
    #code_folding: hide
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = FALSE,
	message = FALSE,
	warning = FALSE, 
	cache=TRUE
)
```

```{r data_packages, message=FALSE, warning=FALSE, include=FALSE}
library(readr)
library(readxl)
library(ggplot2)
library(tidyr)
library(dplyr)
library(kableExtra)
library(lubridate)
library(forcats)
library(stringr)
library(gganimate)
library(plotly)
```

```{r data_transformation, message=FALSE, warning=FALSE, include=FALSE}

tickets<-read_xls("~/GitHub/Aflore/tickets_abril.xls",skip = 2)
# como las fechas estan como carácteres y no date lo convertimos 
tickets$`Created at`<-parse_datetime(tickets$`Created at`)
tickets$`Updated at`<-parse_datetime(tickets$`Updated at`)
tickets$`Closed at`<-parse_datetime(tickets$`Closed at`)
tickets<-tickets %>% mutate(mes=month(`Created at`))









# tickets<-tickets %>% mutate(mes=ifelse(mes=="1","Enero",ifelse(mes=="2","Febrero",ifelse(mes=="3","Marzo",
#                                                                             ifelse(mes=="4","Abril","")))))

#tickets$mes<-parse_factor(tickets$mes,levels = c("Enero","Febrero","Marzo","Abril"))
tickets<-tickets %>% filter(mes!="")

# creando tablas resumen
tickets_mes<-tickets %>% count(mes,Title) %>% pivot_wider(names_from = mes,values_from = n) %>% arrange(-`3`)

ticket_comercial<-tickets %>% filter(Title %in% c("0001- Devolución de saldos por mayor valor pagado",
                                                  "0002 - Devolución de saldo de seguro",
                                                  "0003 - Inconsistencia con el pago de florines"  ,
                                                  "0004 - Certificación de consejero"   ,
                                                  "0006 - Certificación declaración de renta" ,
                                                  "0007- Estado de cuenta" ,
                                                  "0007-Estado de cuenta"  ,
                                                  "0008 - Solicitud de Paz y Salvo" ,
                                                  "0009 - Derecho de petición" ,
                                                  "0013 - Reintegro Consejero/Nombramiento Líder" ,
                                                  "0014 - Retiro Consejero/Líder"     ,
                                                  "0015 - Quitar y adicionar crédito de un corte",
                                                  "0016 - Revertir crédito",
                                                  "0017 - Mi Aflore - Consejero",
                                                  "0018 - Mi Aflore - Cliente",
                                                  "0019 - Llenada por Consejero",
                                                  "0020 - Llenada por Cliente",
                                                  "0022 - Falla en el proceso de desembolso Digital",
                                                  "0025 - Cancelación póliza",
                                                  "0027 - Problemas PBX",
                                                  "0054 - Problemas o cambios expansión geográfica",
                                                  "0057  - Problemas ARK o base de datos" ,
                                                  "0057 - Problemas ARK o base de datos",
                                                  "0059 - Corregir Abono negativo a capital",
                                                  "0060 - Pago duplicado"  ))
tickets_comercial_tabla<-ticket_comercial %>% count(Title) %>% arrange(-n)

```

```{r promediodiames, echo=FALSE}
# calculando promedios en dias por mes para entregar a eduardo
tickets %>% filter(mes==4) %>% filter(Customer=="Luisa Moreno" | Owner=="Luisa Moreno" ) %>%
  mutate(dia=day(`Closed at`)-day(`Created at`)) %>% select(dia) %>% 
  na.omit() %>% 
  summarise(promedio=mean(dia))

tickets %>% filter(mes==4) %>% filter(Customer=="Natalia Piedrahita" | Owner=="Natalia Piedrahita" ) %>%
  mutate(dia=day(`Closed at`)-day(`Created at`)) %>% select(dia) %>% 
  na.omit() %>% 
  summarise(promedio=mean(dia))

```

# Tickets por mes en todas las áreas

```{r plot1, echo=FALSE, message=FALSE, warning=FALSE,fig.height=15,fig.width=10}
# el title es mas completo que el subgrupo en cuanto a detalles, de preferencia usar el primero, brinda mas data
# plot1<-tickets %>%  ggplot(aes(x=reorder(Title,Title,function(x)length(x))))+geom_bar()+coord_flip()+facet_grid(~mes)+labs(x="",y="conteo")
# ggplotly(plot1)

plot1<-tickets %>% count(mes,Title) %>% ggplot(aes(x=reorder(Title,n),y=n,fill=factor(mes,levels=c("4","3","2","1"))))+geom_bar(stat = "identity",position = "dodge2")+
  coord_flip()+labs(x="",y="conteo")+guides(fill=guide_legend(title="mes"))
ggplotly(plot1)
```

```{r table1, echo=FALSE, message=FALSE, warning=FALSE}
# kbl(tickets_mes)
```

# Tickets por mes en área comercial

```{r plot2, echo=FALSE, message=FALSE, warning=FALSE,fig.height=10,fig.width=10}

plot2<-ticket_comercial %>% count(mes,Title) %>% ggplot(aes(x=reorder(Title,n),y=n,fill=factor(mes,levels=c("4","3","2","1"))))+geom_bar(stat = "identity",position = "dodge2")+coord_flip()+labs(x="",y="conteo")+guides(fill=guide_legend(title="mes"))
ggplotly(plot2)

tickets_comercial_tabla %>% kbl() %>% kable_styling(bootstrap_options = c("striped", "hover", "condensed"))

ticket_comercial %>% count(Group) %>% arrange(-n)%>% kbl() %>% kable_styling(bootstrap_options = c("striped", "hover", "condensed"))

ticket_comercial %>% count(Priority) %>% arrange(-n) %>% kbl() %>% kable_styling(bootstrap_options = c("striped", "hover", "condensed"))

ticket_comercial %>% count(Tags) %>% arrange(-n) %>% kbl() %>% kable_styling(bootstrap_options = c("striped", "hover", "condensed"))


```

# Horas promedio de resolución de ticket por mes

El cálculo se realiza hallando el tiempo que pasa entre la hora de creación del ticket y la hora en que se resuelve/cierra, los valores estan en horas.

```{r table3}
# updated at y closed at son prácticamente lo mismo asi que debo tomarlo como si fuesen la misma variable
# a<-a %>% mutate(dif_created_closed=`Closed at`- `Created at`)
# ticket_comercial %>% mutate(dif_updated_closed=(`Updated at`- `Created at`)/60) %>% ggplot(aes(x=dif_updated_closed))+geom_histogram()+facet_grid(~mes)

ggplotly( ticket_comercial %>% group_by(mes) %>% summarise(dif_updated_closed=(`Updated at`- `Created at`)/3600) %>% arrange(-dif_updated_closed) %>% ggplot(aes(x=as.factor(mes),y=dif_updated_closed,fill=as.factor(mes)))+geom_boxplot()+theme(legend.position = "none")
)

# ticket_comercial %>% group_by(Title,mes) %>% summarise(dif_updated_closed=mean((`Updated at`- `Created at`)/3600)) %>% arrange(-dif_updated_closed) %>%
#   filter(Title %in% c("0022 - Falla en el proceso de desembolso Digital" ,
#                       "0009 - Derecho de petición",
#                       "0017 - Mi Aflore - Consejero",
#                       "0057 - Problemas ARK o base de datos",
#                       "0018 - Mi Aflore - Cliente")) %>%
#   ggplot(aes(x=reorder(Title,dif_updated_closed),y=dif_updated_closed,fill=mes))+geom_bar(stat = "identity",position = "dodge2")+coord_flip()


```

```{r boxplot_by_title,fig.width=10,fig.height=14}
ggplotly(  ticket_comercial %>% group_by(Title) %>% summarise(dif_updated_closed=((`Updated at`- `Created at`)/3600)) %>% arrange(-dif_updated_closed) %>% ggplot(aes(x=Title,y=dif_updated_closed,fill=Title))+geom_boxplot()+theme(legend.position = "none")+coord_flip())

```

```{r plot4,fig.width=10,fig.height=14}
ggplotly(ticket_comercial %>% group_by(Title,mes) %>% summarise(dif_updated_closed=median((`Updated at`- `Created at`)/3600)) %>% arrange(-dif_updated_closed) %>% ggplot(aes(x=reorder(Title,dif_updated_closed),y=dif_updated_closed,fill=factor(mes,levels=c("4","3","2","1"))))+geom_bar(stat = "identity",position = "dodge2")+coord_flip()+guides(fill=guide_legend(title="mes"))+labs(x="",y="horas promedio",title = "Horas promedio de resolución por tipo de ticket")
)

```

# Tickets y tiempo por responsable

```{r plot5}
ggplotly(ticket_comercial %>% count(Customer,Owner) %>% arrange(-n) %>% pivot_longer(cols = c(Customer,Owner),names_to = "variable") %>%filter(value %in% c("Natalia Piedrahita","Luisa Moreno"  )) %>%  ggplot(aes(x=n,y=reorder(value,n),fill=variable))+geom_bar(stat = "identity",position = "dodge")+labs(x="numero de tickets",y="",title = "Número de tickets por responsable",caption = "ENERO a 21 ABRIL"))

```

```{r plot6,fig.height=8,fig.width=8}
ticket_comercial %>% filter(Customer %in% c("Natalia Piedrahita","Luisa Moreno"  )) %>% group_by(Title,Customer) %>% summarise(dif_updated_closed=(median((`Updated at`- `Created at`)/3600))) %>% ggplot(aes(x=Title,y=dif_updated_closed,fill=Customer,label=round(dif_updated_closed)))+geom_bar(stat = "identity",position = "dodge2")+geom_text(position = position_dodge(width = .75))+coord_flip()+labs(x="",y="",title = "Horas promedio de resolución por tipo de ticket")
```

```{r plot7_tickets_dias_laborales}
# ticket_comercial %>% filter(mes=="3") %>% filter(day(`Created at`) %in% c(1,2,3,4,7,8,9,10,11,14,15,16,17,18,21,22,23,24,25,28,29,30,31)) %>% count()
# 
# ticket_comercial %>% filter(mes=="3") %>% filter(!day(`Created at`) %in% c(1,2,3,4,7,8,9,10,11,14,15,16,17,18,22,23,24,25,28,29,30,31)) %>% count()


```
